<?php
ini_set('display_errors', 1); // Enable error display for debugging. REMOVE IN PRODUCTION!
error_reporting(E_ALL);     // Report all types of errors. REMOVE IN PRODUCTION!

session_start();
if (!isset($_SESSION['user_id'])) {
    // For AJAX requests, send a JSON error or redirect if not logged in
    if (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest') {
        header('Content-Type: application/json');
        echo json_encode(['status' => 'error', 'message' => 'Session expired or not logged in. Please log in again.', 'redirect' => 'index.php']);
        exit;
    } else {
        header("location:index.php");
        exit;
    }
}

include './config/connection.php'; // Your database connection
include './common_service/common_functions.php'; // For sanitize_input and get_blood_group_options

$message = '';
$is_ajax_request = isset($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest';

// --- Processing Form Submission ---
if (isset($_POST['submit'])) {
    $response = ['status' => 'error', 'message' => 'An unknown error occurred.'];
    try {
        $patient_name = sanitize_input($_POST['patient_name']);
        $cnic = sanitize_input($_POST['cnic']);
        $dob = sanitize_input($_POST['dob']);
        $age = sanitize_input($_POST['age']);
        $gender = sanitize_input($_POST['gender']);
        $phone_number = sanitize_input($_POST['phone_number']);
        $address = sanitize_input($_POST['address']);
        $blood_group = sanitize_input($_POST['blood_group']);
        $next_appointment_date = sanitize_input($_POST['next_appointment_date']);
        $diseases = sanitize_input($_POST['diseases']);
        $registration_date = date('Y-m-d'); // Automatically set registration date

        // Check for empty required fields
        if (empty($patient_name) || empty($cnic) || empty($dob) || empty($gender) || empty($phone_number) || empty($address)) {
            $response = ['status' => 'error', 'message' => 'Please fill all required fields (Patient Name, Unique ID, DOB, Gender, Phone, Address).'];
        } else if (!is_numeric($age)) {
            $response = ['status' => 'error', 'message' => 'Age must be a number.'];
        } else {
            // Check if CNIC already exists
            $stmt_check_cnic = $con->prepare("SELECT COUNT(*) FROM patients WHERE cnic = :cnic");
            $stmt_check_cnic->bindParam(':cnic', $cnic);
            $stmt_check_cnic->execute();
            if ($stmt_check_cnic->fetchColumn() > 0) {
                $response = ['status' => 'error', 'message' => 'A patient with this Unique ID (CNIC) already exists.'];
            } else {
                $query = "INSERT INTO patients (
                            patient_name, cnic, dob, age, gender, phone_number,
                            address, blood_group, next_appointment_date, diseases, registration_date
                        ) VALUES (
                            :patient_name, :cnic, :dob, :age, :gender, :phone_number,
                            :address, :blood_group, :next_appointment_date, :diseases, :registration_date
                        )";

                $stmt = $con->prepare($query);
                $stmt->bindParam(':patient_name', $patient_name);
                $stmt->bindParam(':cnic', $cnic);
                $stmt->bindParam(':dob', $dob);
                $stmt->bindParam(':age', $age);
                $stmt->bindParam(':gender', $gender);
                $stmt->bindParam(':phone_number', $phone_number);
                $stmt->bindParam(':address', $address);
                $stmt->bindParam(':blood_group', $blood_group);
                $stmt->bindParam(':next_appointment_date', $next_appointment_date);
                $stmt->bindParam(':diseases', $diseases);
                $stmt->bindParam(':registration_date', $registration_date);

                if ($stmt->execute()) {
                    // patient_id is auto-generated by the database's primary key (id)
                    $response = ['status' => 'success', 'message' => 'Patient registered successfully!'];
                } else {
                    $response = ['status' => 'error', 'message' => 'Failed to register patient.'];
                    error_log("Patient registration failed: " . implode(" ", $stmt->errorInfo()));
                }
            }
        }
    } catch (PDOException $ex) {
        error_log("PDO Error on registration: " . $ex->getMessage());
        $response = ['status' => 'error', 'message' => 'Database error: ' . $ex->getMessage()];
    }

    if ($is_ajax_request) {
        header('Content-Type: application/json');
        echo json_encode($response);
        exit;
    } else {
        // For non-AJAX submission, set message and reload or redirect
        $_SESSION['message'] = $response['message'];
        $_SESSION['message_type'] = $response['status'];
        header("Location: add_patient.php"); // Redirect to avoid form resubmission
        exit;
    }
}

// If it's an AJAX request to load the form (not a submission)
if ($is_ajax_request && !isset($_POST['submit'])) {
    ob_start(); // Start output buffering
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <form id="addPatientModalForm" method="post">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label>Patient Name <span class="text-danger">*</span></label>
                            <input type="text" class="form-control form-control-sm rounded-0" name="patient_name" id="patient_name" required/>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label>Unique ID (CNIC) <span class="text-danger">*</span></label>
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control form-control-sm rounded-0" name="cnic" id="cnic" required/>
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary btn-sm" type="button" id="generateCnicBtn">Generate</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label>Date of Birth <span class="text-danger">*</span></label>
                            <div class="input-group date" id="dob_picker" data-target-input="nearest">
                                <input type="date" class="form-control form-control-sm rounded-0" data-target="#dob_picker" name="dob" id="dob" autocomplete="off" required/>
                                <div class="input-group-append" data-target="#dob_picker" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label>Age</label>
                            <input type="number" class="form-control form-control-sm rounded-0" name="age" id="age" readonly/>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label>Gender <span class="text-danger">*</span></label>
                            <select class="form-control form-control-sm rounded-0" name="gender" id="gender" required>
                                <option value="">Select Gender</option>
                                <option value="Male">Male</option>
                                <option value="Female">Female</option>
                                <option value="Other">Other</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label>Phone Number <span class="text-danger">*</span></label>
                            <input type="text" class="form-control form-control-sm rounded-0" name="phone_number" id="phone_number" required/>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label>Address <span class="text-danger">*</span></label>
                            <input type="text" class="form-control form-control-sm rounded-0" name="address" id="address" required/>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label>Blood Group</label>
                            <select class="form-control form-control-sm rounded-0" name="blood_group" id="blood_group">
                                <option value="">Select Blood Group</option>
                                <?php echo get_blood_group_options(''); // Pass empty string for new patient ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label>Next Appointment Date</label>
                            <div class="input-group date" id="next_appointment_date_picker" data-target-input="nearest">
                                <input type="date" class="form-control form-control-sm rounded-0" data-target="#next_appointment_date_picker" name="next_appointment_date" id="next_appointment_date" autocomplete="off"/>
                                <div class="input-group-append" data-target="#next_appointment_date_picker" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <div class="form-group">
                            <label>Diseases</label>
                            <input type="text" class="form-control form-control-sm rounded-0" name="diseases" id="diseases"/>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <div id="form-message" class="mt-2"></div>
                        <button type="submit" name="submit" class="btn btn-primary btn-sm rounded-0">Register Patient</button>
                        <button type="button" class="btn btn-secondary btn-sm rounded-0" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="plugins/moment/moment.min.js"></script>
<script src="plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<link rel="stylesheet" href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">

<script>
    $(function () {
        // Initialize Datepickers
        $('#dob_picker').datetimepicker({
            format: 'YYYY-MM-DD',
            icons: { time: 'fa fa-clock', date: 'fa fa-calendar', up: 'fa fa-arrow-up', down: 'fa fa-arrow-down', previous: 'fa fa-chevron-left', next: 'fa fa-chevron-right', today: 'fa fa-calendar-check-o', clear: 'fa fa-trash', close: 'fa fa-times' }
        });

        $('#next_appointment_date_picker').datetimepicker({
            format: 'YYYY-MM-DD',
            icons: { time: 'fa fa-clock', date: 'fa fa-calendar', up: 'fa fa-arrow-up', down: 'fa fa-arrow-down', previous: 'fa fa-chevron-left', next: 'fa fa-chevron-right', today: 'fa fa-calendar-check-o', clear: 'fa fa-trash', close: 'fa fa-times' },
            minDate: moment().startOf('day')
        });

        // Age Calculation
        function calculateAge() {
            var dobString = $('#dob').val();
            if (dobString) {
                var dob = moment(dobString, 'YYYY-MM-DD');
                if (dob.isValid()) {
                    var today = moment();
                    var age = today.diff(dob, 'years');
                    $('#age').val(age);
                } else { $('#age').val(''); }
            } else { $('#age').val(''); }
        }

        $('#dob').on('change.datetimepicker', calculateAge);
        // No initial calculateAge call for new patient as DOB is usually empty

        // --- Unique ID (CNIC) Generation ---
        function generateUniqueCnic() {
            // Generates a simple pseudo-unique ID using timestamp and a random part
            // For production, consider more robust UUID generation or a server-side mechanism
            // that checks for true uniqueness in the database before assigning.
            const timestamp = Date.now().toString(36).toUpperCase(); // e.g., '1BBA08678F'
            const randomPart = Math.random().toString(36).substring(2, 7).toUpperCase(); // e.g., 'A1B2C'
            const uniqueId = `PN-${timestamp}-${randomPart}`; // Patient Number
            $('#cnic').val(uniqueId);
        }

        // Event listener for the "Generate" button
        $('#generateCnicBtn').on('click', function() {
            generateUniqueCnic();
        });

        // Auto-generate CNIC when the form is loaded, if the field is empty
        // This ensures a unique ID is ready for new registrations
        if ($('#cnic').val() === '') {
            generateUniqueCnic();
        }


        // --- AJAX Form Submission ---
        $('#addPatientModalForm').on('submit', function(e) {
            e.preventDefault(); // Prevent default form submission

            var formData = $(this).serialize(); // Serialize form data
            var formMessage = $('#form-message');

            $.ajax({
                url: 'add_patient.php', // Submit to this same file
                type: 'POST',
                data: formData + '&submit=1', // Add submit flag for PHP processing
                dataType: 'json', // Expect JSON response
                success: function(response) {
                    if (response.status === 'success') {
                        formMessage.html('<div class="alert alert-success">' + response.message + '</div>');
                        // Clear the form for next entry (optional, depends on UX)
                        $('#addPatientModalForm')[0].reset();
                        $('#age').val(''); // Clear age field explicitly
                        // Re-generate CNIC for a new entry
                        generateUniqueCnic();

                        // Close modal and reload parent page after success
                        setTimeout(function() {
                            $('#addPatientModal').modal('hide'); // Hide the modal
                            location.reload(); // Reload patients_list.php to show new patient
                        }, 1500);
                    } else {
                        formMessage.html('<div class="alert alert-danger">' + response.message + '</div>');
                    }
                },
                error: function(xhr, status, error) {
                    console.error("AJAX Error: ", status, error, xhr.responseText);
                    formMessage.html('<div class="alert alert-danger">An error occurred during submission. Please try again.</div>');
                }
            });
        });
    });
</script>
<?php
    echo ob_get_clean(); // End output buffering and echo the content
    exit; // Stop further execution for AJAX requests
}

// --- NORMAL PAGE RENDERING (for direct access to add_patient.php, if any) ---
// This part will only run if add_patient.php is accessed directly, not via AJAX.
// It's good practice to have this as a fallback.
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register New Patient - KDCS</title>
    <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="dist/css/adminlte.min.css">
    <link rel="stylesheet" href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">
<div class="wrapper">
    <?php include './config/header.php'; ?>
    <?php include './config/sidebar.php'; ?>

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Register New Patient</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="dashboard.php">Home</a></li>
                            <li class="breadcrumb-item"><a href="patients_list.php">Patients List</a></li>
                            <li class="breadcrumb-item active">Register Patient</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Patient Registration Form</h3>
                            </div>
                            <form id="addPatientFormFull" method="post" action="add_patient.php">
                                <div class="card-body">
                                    <?php if (!empty($message)): ?>
                                        <div class="alert <?php echo (isset($_SESSION['message_type']) && $_SESSION['message_type'] == 'success') ? 'alert-success' : 'alert-danger'; ?>">
                                            <?php echo htmlspecialchars($message); ?>
                                            <?php unset($_SESSION['message']); unset($_SESSION['message_type']); ?>
                                        </div>
                                    <?php endif; ?>
                                    <div class="row">
                                        <div class="col-lg-4 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label>Patient Name <span class="text-danger">*</span></label>
                                                <input type="text" class="form-control form-control-sm rounded-0" name="patient_name" id="patient_name_full" required/>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label>Unique ID (CNIC) <span class="text-danger">*</span></label>
                                                <div class="input-group input-group-sm">
                                                    <input type="text" class="form-control form-control-sm rounded-0" name="cnic" id="cnic_full" required/>
                                                    <div class="input-group-append">
                                                        <button class="btn btn-outline-secondary btn-sm" type="button" id="generateCnicBtnFull">Generate</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label>Date of Birth <span class="text-danger">*</span></label>
                                                <div class="input-group date" id="dob_picker_full" data-target-input="nearest">
                                                    <input type="date" class="form-control form-control-sm rounded-0" data-target="#dob_picker_full" name="dob" id="dob_full" autocomplete="off" required/>
                                                    <div class="input-group-append" data-target="#dob_picker_full" data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label>Age</label>
                                                <input type="number" class="form-control form-control-sm rounded-0" name="age" id="age_full" readonly/>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label>Gender <span class="text-danger">*</span></label>
                                                <select class="form-control form-control-sm rounded-0" name="gender" id="gender_full" required>
                                                    <option value="">Select Gender</option>
                                                    <option value="Male">Male</option>
                                                    <option value="Female">Female</option>
                                                    <option value="Other">Other</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label>Phone Number <span class="text-danger">*</span></label>
                                                <input type="text" class="form-control form-control-sm rounded-0" name="phone_number" id="phone_number_full" required/>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label>Address <span class="text-danger">*</span></label>
                                                <input type="text" class="form-control form-control-sm rounded-0" name="address" id="address_full" required/>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label>Blood Group</label>
                                                <select class="form-control form-control-sm rounded-0" name="blood_group" id="blood_group_full">
                                                    <option value="">Select Blood Group</option>
                                                    <?php echo get_blood_group_options(''); ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-lg-2 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label>Next Appointment Date</label>
                                                <div class="input-group date" id="next_appointment_date_picker_full" data-target-input="nearest">
                                                    <input type="date" class="form-control form-control-sm rounded-0" data-target="#next_appointment_date_picker_full" name="next_appointment_date" id="next_appointment_date_full" autocomplete="off"/>
                                                    <div class="input-group-append" data-target="#next_appointment_date_picker_full" data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12">
                                            <div class="form-group">
                                                <label>Diseases</label>
                                                <input type="text" class="form-control form-control-sm rounded-0" name="diseases" id="diseases_full"/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer text-center">
                                    <button type="submit" name="submit" class="btn btn-primary btn-sm rounded-0">Register Patient</button>
                                    <a href="patients_list.php" class="btn btn-secondary btn-sm rounded-0">Cancel</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <?php include './config/footer.php'; ?>
</div>

<script src="plugins/jquery/jquery.min.js"></script>
<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="dist/js/adminlte.min.js"></script>
<script src="plugins/moment/moment.min.js"></script>
<script src="plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>

<script>
    $(function () {
        // Initialize Datepickers for full page
        $('#dob_picker_full').datetimepicker({
            format: 'YYYY-MM-DD',
            icons: { time: 'fa fa-clock', date: 'fa fa-calendar', up: 'fa fa-arrow-up', down: 'fa fa-arrow-down', previous: 'fa fa-chevron-left', next: 'fa fa-chevron-right', today: 'fa fa-calendar-check-o', clear: 'fa fa-trash', close: 'fa fa-times' }
        });

        $('#next_appointment_date_picker_full').datetimepicker({
            format: 'YYYY-MM-DD',
            icons: { time: 'fa fa-clock', date: 'fa fa-calendar', up: 'fa fa-arrow-up', down: 'fa fa-arrow-down', previous: 'fa fa-chevron-left', next: 'fa fa-chevron-right', today: 'fa fa-calendar-check-o', clear: 'fa fa-trash', close: 'fa fa-times' },
            minDate: moment().startOf('day')
        });

        // Age Calculation for full page
        function calculateAgeFull() {
            var dobString = $('#dob_full').val();
            if (dobString) {
                var dob = moment(dobString, 'YYYY-MM-DD');
                if (dob.isValid()) {
                    var today = moment();
                    var age = today.diff(dob, 'years');
                    $('#age_full').val(age);
                } else { $('#age_full').val(''); }
            } else { $('#age_full').val(''); }
        }

        $('#dob_full').on('change.datetimepicker', calculateAgeFull);
        // No initial calculateAgeFull call as DOB is usually empty for new patient


        // --- Unique ID (CNIC) Generation for full page ---
        function generateUniqueCnicFull() {
            const timestamp = Date.now().toString(36).toUpperCase();
            const randomPart = Math.random().toString(36).substring(2, 7).toUpperCase();
            const uniqueId = `PN-${timestamp}-${randomPart}`;
            $('#cnic_full').val(uniqueId);
        }

        // Event listener for the "Generate" button on full page
        $('#generateCnicBtnFull').on('click', function() {
            generateUniqueCnicFull();
        });

        // Auto-generate CNIC when the full page loads, if the field is empty
        if ($('#cnic_full').val() === '') {
            generateUniqueCnicFull();
        }
    });
</script>
</body>
</html>